emersion/slurp

include/slurp.h, main.c
Fixes memory leaks. Just added a struct to track the seats, don't know if you want to structure it differently.
Also includes a small fix to remove destroyed outputs from list.
=> Track seats to free them on exit

include/slurp.h, main.c
I was seeing a segfault while testing, so ran it in valgrind.
```
==890== Memcheck, a memory error detector
==890== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==890== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==890== Command: ./slurp
==890==
==890== Invalid read of size 1
==890==    at 0x40294C: output_frame_handle_done (main.c:258)
==890==    by 0x813DA0D: ffi_call_unix64 (in /nix/store/qwmw5ddw8lk2pz4fy3irp87vj1cawvjh-libffi-3.2.1/lib/libffi.so.6.0.4)
==890==    by 0x813C9D2: ffi_call (in /nix/store/qwmw5ddw8lk2pz4fy3irp87vj1cawvjh-libffi-3.2.1/lib/libffi.so.6.0.4)
==890==    by 0x53826D3: wl_closure_invoke (in /nix/store/iqcr4c8d2pmr19g4i8323jf8j48hrpvh-wayland-1.16.0/lib/libwayland-client.so.0.3.0)
==890==    by 0x537EEE8: …
```
=> Fix use-after-free: fix frame callback running after destroy_output

include/slurp.h, main.c, render.c
This looked doable. Is any more bookkeeping needed? maybe a `wl_keyboard_destroy` somewhere?
=> Abort on escape

main.c
`slurp -h` displays `#rrggbb` for colours, while slurp accepts `#rrggbbaa`.
=> Display alpha in usage section

include/slurp.h, main.c, render.c
This builds on #25, sorry.
Adds support for selection across multiple outputs.
=> Support selection across multiple outputs

main.c, slurp.1.scd
Closes #1.
I hope my code is up to standards. I've never touched C before.
=> Add user-defined output formatting

include/slurp.h, main.c, render.c, slurp.1.scd
Sorry for building on #27. I can probably rebase if neccesary. Actual compare view is at https://github.com/yorickvP/slurp/compare/multi-outputs...yorickvP:select-predef
This accepts a list of regions on stdin (if stdin is non-interactive),
i.e. `echo -e "2565,31 1855x1404\n4425,31 690x1404" | slurp`
Dragging still works, but a single click will select the hovered region. This can be used to implement some features:
#18: `swaymsg -t get_outputs | jq -r '.[] | select(.active) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | slurp`
#16: `swaymsg -t get_tree | jq -r '.. | (.nodes? // empty)[] | select(.pid and .visible) | .rect | "\(.x),\(.y) \(.width)x\(.height)"'  | slurp`
I need to figure out a jq that filters visible windows. Not sure if there are any other usecases. This maybe should …
=> Accept list of predefined regions on stdin for quick selection

include/slurp.h, main.c
Hi,
This is a feature add.
When dragging the selection, you can  use the modifier `space` key to move your selection around 
Video:
Result on second screen (not from the same recording and my screens aren't aligned):
=> Move selection on `space` keypress

main.c
Fix not being able to select the pixels at bottom and right edges of the
screen by including corner positions in the selection.
Selecting from top left of screen to bottom right, before:
```
$ slurp
0,0 1919x1079
```
after:
```
$ slurp
0,0 1920x1080
```
=> Include corner positions in selection

.build.yml, include/slurp.h, main.c, meson.build
Fix #36
The first commit contains debug code.
=> Take into account keymap

include/slurp.h, main.c
Selection by a single touch point, similar to the mouse.
Boilerplate code for touch handling is added.
Three pieces of code are moved to separate functions from handle_pointer* methods so as to be reused by the corresponding handle_touch* one.
=> #29: adding touch support 

include/slurp.h, main.c, render.c
Added separated structs as per discussion in #50.
=> separated pointer and touch selection states

main.c
Slurp has this strange behavior where you start slurp and the surface is immediately fullscreen, but if your cursor is already positioned in the selection area (when you provide your own boxes) it doesn't highlight them. Worse, if you click within a selection area without moving your cursor it doesn't output the selection area you clicked on!
This PR changes that so the selection is updated on pointer enter as well as motion, allowing a selection to be immediately active when slurp starts. The first commit doesn't change anything, just rearranges some functions in main so I can use them without declaring them elsewhere. The second function does all the changes, by moving some of the motion code into `seat_update_selection` and calling it in handle_enter as well. PTAL.
=> Fix empty selection when user doesn't move their cursor

main.c, slurp.1.scd
This makes output it a bit more easily readable in scripting.
=> Allow a custom formatting to not have a newline in the end

include/slurp.h, main.c, render.c, slurp.1.scd
This PR contains three related changes:
1. Fix a bug where if you hover over a choice box, then move away the choice box stays highlighted
2. Always render choice boxes as a different color, to make it easier to identify them, and add an option to specify the color (this is what I'm least sure about).
3. Add an option to force the user to select a choicebox (disallow custom rectangles). This will interact with #60 and whichever one is merged last will probably need to be updated to at least add documentation on how they interact.
If you'd prefer, I can split these out into seperate PRs.
=> Force select

main.c
Because the coordinate is 0 indexed, "greater than", not "greater or
equal than" has to be used here (imagine a 1x1 box, it only contains the
coordinates (0,0), not (1,1)).
This fixes output selection printing the wrong display name (as it uses
the upper left corner of the selection to figure out the display, it
falls into this edge case).
=> Fix off-by-one error in in_box function

main.c
Just like how pointer_handle_motion marks the old state as dirty,
pointer_handle_enter should also mark the old state as dirty.
This fixes #87.
Not sure whether leave or enter is preferred, but enter seems nicer
because that's closer to where the state is changed.
There is still a race condition left, although it's very unlikely to
happen:
1. handle_motion or handle_enter is called. The current selection is on output A.
2. The output A is marked dirty
3. render() is called async, and handles the redraw of A, using the old
selection.
4. render() marks A a clean
5. move_seat is called from handle_motion or handle_enter. This updates
the selection to point to output B and B is marked dirty
6. B will be redraw on further events, but A will forever remain in a
=> Mark moved-away from outputs as dirty

main.c
Fix #86.
Old behavior:
When the mouse is pressed, `has_selection` is set to `true`, and the `anchor` is set, but the selection itself is not actually filled. When the mouse is release, `has_selection` is true so the [outdated] value of `selection` is read.
New behavior:
`has_selection` is only set to true when the `selection` is set, i.e. on mouse move.
All of `-p`, `-r` and `slurp` without arguments still work fine, but some testing may be needed - I don't fully understand all the logic myself.
=> has_selection is true only after moving the mouse

render.c
~This PR adds a `-D` argument that lets the user specify the text color for the displayed dimensions.~
This PR adds the ability to use the border color for the text rendering
https://user-images.githubusercontent.com/446970/140625682-0846d26f-584c-474d-903c-06e9964d4ff5.mp4
=> Render dimensions with same color as the border

include/slurp.h, main.c, render.c, slurp.1.scd
User can pass the `-F` option and specify one of standard CSS2 generic
font family names. It'll default to the sans family if not specified and
only be visible in combination with the `-d` option.
=> render: Allow the user to specify which font family to use

main.c, slurp.1.scd
With the '-x' flag slurp will calculate the x and y coordinates relative
to the position of the output the selection starts on (upper left corner).
If the selection spans over multiple outputs it will be cropped to the
intersection with the output.
=> Print output local coordinates

meson.build
To build this project, you must have the staging/cursor-shape protocol
which was added in 1.32.
=> Update required version of wayland-protocols to >1.32

README.md
This is useful for screenshots. The previously present example is simpler, but unsuitable for screenshots as it results in pictures with border on three sides (i.e. top side doesn't have border). This doesn't look well.
=> Add example how to select windows without border under Sway

main.c
previously, cursor_shape_manager was not handled and registered, which can lead to slurp incorrectly loading the entire cursor theme, despite the compositor supporting cursor_shape_manager.
=> fix handling cursor_shape_manager

README.md
The grim project was moved to freedesktop, as stated in the previously linked page
=> Update link to grim in README

include/slurp.h, main.c
Pressing Shift still changes the aspect ratio, but that is only reflected while resizing a selection (not while hovering). 
Closes #131
=> Enable Shift key only while resizing current selection
